### ISSUE TITLE
error to plot camera.

### ISSUE THREAD

**Issue by NoePity2** [petercorke/machinevision-toolbox-python#2]
Dear all,

when I want to use the plot_camera method I get the error: "self.camera.T.A is not defined". I changed that attribute to _T as it appears in the attributes of the CentralCamera class and it didn't work either. When I used self.pose instead of self._T in various methods of the CentralCamera class, the error was removed.

Regards,

Noé Aldana

**Comment by petercorke** [comment]
`plot_camera` method is deprecated for a while, try `plot` instead.  I suspect you an old version, please update and let me know how it goes.
